## 1D Convolutions with PyTorch

Click [here](https://pytorch.org/docs/stable/generated/torch.nn.Conv1d.html) for the full documentation of PyTorch's 1D Convolutional layer.

In [1]:
import numpy as np

import torch
import torch.nn as nn

In [2]:
# my 1 dimensional data
x = torch.tensor([[[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]]) # shape is (batch_size, in_channels, input_length)
print(x.shape)
print(x)

torch.Size([1, 1, 10])
tensor([[[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]])


![image.png](torch-conv1d.png)

In [3]:
# Create 1d conv layer
in_channels = 1
out_channels = 1
kernel_size = 3
my_conv1d = nn.Conv1d(in_channels, out_channels, kernel_size, bias=False) # stride=1, padding=0, padding_mode='zeros', dilation=1

# Overwrite weights & bias
my_conv1d.weight = nn.Parameter(torch.ones(out_channels, in_channels, kernel_size)) # shape is (out_channels, in_channels, kernel_size)
 
for p in my_conv1d.parameters():
    print(p.shape)
    print(p)

torch.Size([1, 1, 3])
Parameter containing:
tensor([[[1., 1., 1.]]], requires_grad=True)


![image.png](in-out-shapes.png)

In [4]:
with torch.no_grad():
    output = my_conv1d(x)
    print(f'input    : {x.numpy()}')
    print(f'kernel   : {my_conv1d.weight.numpy()}')
    print(f'output   : {output.numpy()}')
    print(f'out shape: {output.numpy().shape}')

input    : [[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]]
kernel   : [[[1. 1. 1.]]]
output   : [[[ 3.  6.  9. 12. 15. 18. 21. 24.]]]
out shape: (1, 1, 8)


In [5]:
# Implementation using numpy and for loops
f = np.array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
g = np.array([1., 1., 1.])

l_in = x.shape[2]
padding = 0
dilation = 1
kernel_size = 3
stride = 1

l_out = ((l_in + 2*padding - dilation*(kernel_size - 1) - 1)/stride) + 1

# slide the filter along input window, multiply, sum
output = []
for i in range(int(l_out)):
    print(f'Step {i}: sum({f[i:i+kernel_size]}*{g}) = {np.sum(g*f[i:i+kernel_size])}')
    output.append(np.sum(g*f[i:i+kernel_size]))
output = np.stack(output)

print(f'Final : {output}')

Step 0: sum([0. 1. 2.]*[1. 1. 1.]) = 3.0
Step 1: sum([1. 2. 3.]*[1. 1. 1.]) = 6.0
Step 2: sum([2. 3. 4.]*[1. 1. 1.]) = 9.0
Step 3: sum([3. 4. 5.]*[1. 1. 1.]) = 12.0
Step 4: sum([4. 5. 6.]*[1. 1. 1.]) = 15.0
Step 5: sum([5. 6. 7.]*[1. 1. 1.]) = 18.0
Step 6: sum([6. 7. 8.]*[1. 1. 1.]) = 21.0
Step 7: sum([7. 8. 9.]*[1. 1. 1.]) = 24.0
Final : [ 3.  6.  9. 12. 15. 18. 21. 24.]


In [6]:
my_conv1d = nn.Conv1d(in_channels=1, out_channels=2, kernel_size=3, bias=False) # stride=1, padding=0, padding_mode='zeros', dilation=1
 
for p in my_conv1d.parameters():
    print(p.shape)
    print(p)

torch.Size([2, 1, 3])
Parameter containing:
tensor([[[-0.1350, -0.3093,  0.4472]],

        [[-0.0927, -0.3136,  0.2532]]], requires_grad=True)


In [7]:
my_conv1d = nn.Conv1d(in_channels=1, out_channels=2, kernel_size=3, bias=False) # stride=1, padding=0, padding_mode='zeros', dilation=1
my_conv1d.weight = nn.Parameter(torch.tensor([[[1., 1., 1.]],
                                              [[2., 2., 2.]]])) # shape is (out_channels, in_channels, kernel_size)
 
with torch.no_grad():
    output = my_conv1d(x)
    print(f'input    : {x.numpy()}')
    print(f'kernel   :\n{my_conv1d.weight.numpy()}')
    print(f'output   :\n{output.numpy()}')
    print(f'out shape: {output.numpy().shape}')

input    : [[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]]
kernel   :
[[[1. 1. 1.]]

 [[2. 2. 2.]]]
output   :
[[[ 3.  6.  9. 12. 15. 18. 21. 24.]
  [ 6. 12. 18. 24. 30. 36. 42. 48.]]]
out shape: (1, 2, 8)


---

In [8]:
my_conv1d = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3, bias=False, stride=1, padding=0, padding_mode='zeros', dilation=1)
my_conv1d.weight = nn.Parameter(torch.ones(1, 1, 3))
 
with torch.no_grad():
    output = my_conv1d(x)
    print(f'input    : {x.numpy()}')
    print(f'kernel   : {my_conv1d.weight.numpy()}')
    print(f'output   : {output.numpy()}')
    print(f'out shape: {output.numpy().shape}')

input    : [[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]]
kernel   : [[[1. 1. 1.]]]
output   : [[[ 3.  6.  9. 12. 15. 18. 21. 24.]]]
out shape: (1, 1, 8)


In [9]:
my_conv1d = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3, bias=False, stride=2, padding=0, padding_mode='zeros', dilation=1)
my_conv1d.weight = nn.Parameter(torch.ones(1, 1, 3))
 
with torch.no_grad():
    output = my_conv1d(x)
    print(f'input    : {x.numpy()}')
    print(f'kernel   : {my_conv1d.weight.numpy()}')
    print(f'output   : {output.numpy()}')
    print(f'out shape: {output.numpy().shape}')

input    : [[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]]
kernel   : [[[1. 1. 1.]]]
output   : [[[ 3.  9. 15. 21.]]]
out shape: (1, 1, 4)


In [10]:
my_conv1d = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3, bias=False, stride=1, padding=1, padding_mode='zeros', dilation=1)
my_conv1d.weight = nn.Parameter(torch.ones(1, 1, 3))
 
with torch.no_grad():
    output = my_conv1d(x)
    print(f'input    : {x.numpy()}')
    print(f'kernel   : {my_conv1d.weight.numpy()}')
    print(f'output   : {output.numpy()}')
    print(f'out shape: {output.numpy().shape}')

input    : [[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]]
kernel   : [[[1. 1. 1.]]]
output   : [[[ 1.  3.  6.  9. 12. 15. 18. 21. 24. 17.]]]
out shape: (1, 1, 10)


In [11]:
my_conv1d = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3, bias=False, stride=1, padding=0, padding_mode='zeros', dilation=2)
my_conv1d.weight = nn.Parameter(torch.ones(1, 1, 3))
 
with torch.no_grad():
    output = my_conv1d(x)
    print(f'input    : {x.numpy()}')
    print(f'kernel   : {my_conv1d.weight.numpy()}')
    print(f'output   : {output.numpy()}')
    print(f'out shape: {output.numpy().shape}')

input    : [[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]]
kernel   : [[[1. 1. 1.]]]
output   : [[[ 6.  9. 12. 15. 18. 21.]]]
out shape: (1, 1, 6)


In [16]:
my_conv1d = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=2, bias=False, stride=1, padding=0, padding_mode='zeros', dilation=1)
my_conv1d.weight = nn.Parameter(torch.ones(1, 1, 2)/2)
 
with torch.no_grad():
    output = my_conv1d(x)
    print(f'input    : {x.numpy()}')
    print(f'kernel   : {my_conv1d.weight.numpy()}')
    print(f'output   : {output.numpy()}')
    print(f'out shape: {output.numpy().shape}')

input    : [[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]]
kernel   : [[[0.5 0.5]]]
output   : [[[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5]]]
out shape: (1, 1, 9)


### Causal Conv1D

![image.png](causalconv1d.png)

In [13]:
class CausalConv1d(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size, dilation=1):
        super(CausalConv1d, self).__init__()
        self.padding = (kernel_size - 1)*dilation
        self.conv1d = nn.Conv1d(in_channels, out_channels, kernel_size, bias=False, padding=self.padding, dilation=dilation)

    def forward(self, x):
        x = self.conv1d(x)
        x = x[:, :, :-self.padding] # drop the right padded calculations
        return x

In [14]:
my_conv1d = CausalConv1d(in_channels=1, out_channels=1, kernel_size=3) # padding is (3 - 1)*1 = 2
my_conv1d.conv1d.weight = nn.Parameter(torch.ones(out_channels, in_channels, kernel_size))

with torch.no_grad():
    output = my_conv1d(x)
    print(f'input    : {x.numpy()}')
    print(f'kernel   : {my_conv1d.conv1d.weight.numpy()}')
    print(f'output   : {output.numpy()}')
    print(f'out shape: {output.numpy().shape}')

input    : [[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]]
kernel   : [[[1. 1. 1.]]]
output   : [[[ 0.  1.  3.  6.  9. 12. 15. 18. 21. 24.]]]
out shape: (1, 1, 10)
